### ISSUE TITLE
Unexpected Change in State.

### ISSUE THREAD

**Issue by the-first-elder** [Steemhunt/mint.club-v2-contract#66]
If  user A uses the same `BondParams::reserve` token address twice while calling the  `BondParams::createToken` ... The generated token would be pushed twice into the array at 

https://github.com/Steemhunt/mint.club-v2-contract/blob/0665adb8caa31f07ac1f0f78763aaa1e950526a6/contracts/MCV2_Bond.sol#L254

The array Will return a wrong user Length cause of duplication.
https://github.com/Steemhunt/mint.club-v2-contract/blob/0665adb8caa31f07ac1f0f78763aaa1e950526a6/contracts/MCV2_Bond.sol#L505

But if User B calls  the `BondParams::createToken` with the same address as userA. An override of information occurs here

https://github.com/Steemhunt/mint.club-v2-contract/blob/0665adb8caa31f07ac1f0f78763aaa1e950526a6/contracts/MCV2_Bond.sol#L187

The Previous creator which is userA  is changed to User B.

**Comment by sydneyitguy** [comment]
https://github.com/Steemhunt/mint.club-v2-contract/blob/0665adb8caa31f07ac1f0f78763aaa1e950526a6/contracts/MCV2_Bond.sol#L254

This simply pushes the new token address (created by `create2` operation with a salt of the new token symbol) to the last index of the tokens array.

https://github.com/Steemhunt/mint.club-v2-contract/blob/0665adb8caa31f07ac1f0f78763aaa1e950526a6/contracts/MCV2_Bond.sol#L227

If another user calls the createToken function with the same `reserveToken`, it will just add another token (with a different symbol, name, supply, bonding curve parameters and contract address) to the tokens array. That's acceptable because it's a different token that uses the same reserve token as collateral.

It cannot produce the same token contract address, as this is prevented here:

https://github.com/Steemhunt/mint.club-v2-contract/blob/0665adb8caa31f07ac1f0f78763aaa1e950526a6/contracts/MCV2_Bond.sol#L235

I don't think using the same reserve token can cause an unexpected change in state. Could you check it again and provide me with proof of concept call parameters (or test cases) if possible?

**Comment by the-first-elder** [comment]
Just re tried the Test. It Reverts with this Error ` MCV2_Bond__TokenSymbolAlreadyExists()` .  Sorry bout that.


![Screenshot from 2023-12-19 12-48-47](https://github.com/Steemhunt/mint.club-v2-contract/assets/30228336/b851578e-a3b9-4601-af06-9a46191559e3)
